services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "8082:5432"
    networks:
      - bridge
  module11:
#    build: .
    image: "module11"
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
